name: QJsonStruct build matrix - cmake

on: 
  push:

jobs:
  build:
    strategy:
      matrix:
        qt_version: [6.1.0]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        include: 
          - platform: windows-latest
            qtarch: win64_msvc2019_64
          - platform: ubuntu-latest
      fail-fast: false
        
    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Checking out sources
        uses: actions/checkout@master
# =========================================================================================================
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: QtCache-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.qt_version }}
      - name: Installing Qt - ${{ matrix.arch }}
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_version }}
          arch: ${{ matrix.qtarch }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
# =========================================================================================================
      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build .
      - name: Run
        shell: bash
        run: |
          cd ./build/
          # Yeah nmake just ignores CMAKE_BUILD_TYPE, falling back to Debug 
          ctest . -VV -C Debug
